import responses

# Import the actual logic from our script
from src.bronze.ingest_fraud_api import fetch_fraud_blacklist


@responses.activate
def test_fetch_fraud_blacklist_success():
    # 1. Arrange: Tell the 'responses' library to intercept any calls to this URL
    # Notice we can use ANY fake URL here, because 'responses' intercepts the request
    # before it ever reaches the internet!
    api_url = "https://fake-api.local/v1/blacklist"

    # Mock payload should match the structure generated by our data-generator (a list of entities)
    mock_payload = [
        {"fraud_id": "123", "entity_type": "SSN", "malicious_value": "000-00-0000"},
        {
            "fraud_id": "456",
            "entity_type": "Email",
            "malicious_value": "scammer@bad.com",
        },
    ]

    responses.add(responses.GET, api_url, json=mock_payload, status=200)

    # 2. Act: Call our function
    result = fetch_fraud_blacklist(api_url, "fake-test-token")

    # 3. Assert: Verify the function correctly returned the JSON payload
    assert isinstance(result, list)
    assert len(result) == 2
    assert result[0]["entity_type"] == "SSN"
